gpp=g++

all:
	$(gpp) -std=gnu++0x -O2 -pthread -I . scTurtle32.cpp -o scTurtle32
	$(gpp) -std=gnu++0x -O2 -pthread -I . scTurtle64.cpp -o scTurtle64
	$(gpp) -std=gnu++0x -O2 -pthread -I . cTurtle64.cpp -o cTurtle64
	$(gpp) -std=gnu++0x -O2 -pthread -I . cTurtle32.cpp -o cTurtle32
	$(gpp) -std=gnu++0x -O2 -I . aTurtle32.cpp -o aTurtle32
	$(gpp) -std=gnu++0x -O2 -I . aTurtle64.cpp -o aTurtle64
